name: windows

on: [push, pull_request]

jobs:

  windows-build:
    runs-on: ${{ matrix.windows-version }}
    strategy:
      fail-fast: false
      matrix:
        windows-version:
          - 'windows-2019'
          - 'windows-latest'
    env:
      CXXFLAGS: /MP
      BUILD_TYPE: Release

    steps:
      - name: Sync repository
        uses: actions/checkout@v3
        
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      
      - name: Conan profile
        run: conan profile detect
      
      - name: Cache Conan
        uses: actions/cache@v3
        with:
          path: $HOME/.conan2/
          key: ${{ matrix.os }}-${{ hashFiles('**/lockfiles') }}
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v3.3.0
        with:
          version: '5.15.2'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/qt_installation/'
          cache: 'true'
          cache-key-prefix: 'install-qt-action'
      
      - name: Install dependencies
        run: conan install . -s compiler.cppstd=17 --build=missing -s build_type=Release --output-folder=${{github.workspace}}/build
    
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE="${{github.workspace}}/build/conan_toolchain.cmake" -DCMAKE_BUILD_TYPE==Release -DBUILDING_WITH_CONAN=ON
    
      - name: Build Plotjuggler
        shell: pwsh
        run: cmake --build ${{github.workspace}}/build
 
